name: Connect to AWS DocumentDB and Setup MongoDB

on:
  push:
    branches:
      - main

jobs:
  connect-to-documentdb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MongoDB shell
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -sc)/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org-shell

    - name: Connect to AWS DocumentDB
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
        MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
        DOCUMENTDB_CLUSTER_ENDPOINT: ${{ secrets.DOCUMENTDB_CLUSTER_ENDPOINT }}
      run: |
        echo "Creating MongoDB instance and linking to DB"
        mongo "mongodb://${{ env.MONGO_INITDB_ROOT_USERNAME }}:${{ env.MONGO_INITDB_ROOT_PASSWORD }}@${{ env.DOCUMENTDB_CLUSTER_ENDPOINT }}/admin?ssl=true&sslAllowInvalidCertificates=true" --eval 'db.createCollection("exampleCollection")'

